name: "Documentation"
on: ["push"]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"