name: "Documentation"
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "doc/"
          pre-build-command: python -m pip install -r requirements-doc.txt