name: "Static analysis"

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: "Install dependencies"
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: "Run pylint"
      run: pylint src/host
      continue-on-error: true
    - name: "Run flake8"
      run: flake8 src/host
      continue-on-error: true
    - name: "Run mypy"
      run: mypy src/host
      continue-on-error: true
